export enum OrderActions {
  CREATE = 'ORDER_CREATE',
  CHANGE_STATUS = 'CHANGE_STATUS',
  GET_ALL = 'ORDER_GET_ALL',
  GET_ONE_BY_ID = 'ORDER_GET_ONE_BY_ID',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED'
}
